Repository gd-edit/GDAPI, pull requests merged in 2020-05, with the labels that each got.

#56 Compact ID reallocation
  GDAPI/GDAPI.Tests/Application/Editors/EditorTests.cs
  GDAPI/GDAPI.Tests/Application/Editors/IDMigrationTests.cs
  GDAPI/GDAPI.Tests/Functions/Extensions/RangeExtensionsTests.cs
  GDAPI/GDAPI.Tests/Objects/GeometryDash/LevelObjectIDUsageTests.cs
  GDAPI/GDAPI/Application/Editors/Editor.cs
  GDAPI/GDAPI/Enumerations/GeometryDash/LevelObjectIDType.cs
  GDAPI/GDAPI/Enumerations/IDMigrationMode.cs
  GDAPI/GDAPI/Functions/Comparers/GenericRangeComparers.cs
  GDAPI/GDAPI/Functions/Comparers/RangeComparers.cs
  GDAPI/GDAPI/Functions/Extensions/DictionaryExtensions.cs
  GDAPI/GDAPI/Functions/Extensions/GenericListExtensions.cs
  GDAPI/GDAPI/Functions/Extensions/RangeExtensions.cs
  GDAPI/GDAPI/Objects/General/ProgressReporter.cs
  GDAPI/GDAPI/Objects/General/SourceTargetPair.cs
  GDAPI/GDAPI/Objects/General/SourceTargetRange.cs
  GDAPI/GDAPI/Objects/GeometryDash/ColorChannels/ColorChannel.cs
  GDAPI/GDAPI/Objects/GeometryDash/ColorChannels/LevelColorChannels.cs
  GDAPI/GDAPI/Objects/GeometryDash/General/Level.cs
  GDAPI/GDAPI/Objects/GeometryDash/General/LevelObjectColorIDUsage.cs
  GDAPI/GDAPI/Objects/GeometryDash/General/LevelObjectGroupIDUsage.cs
  GDAPI/GDAPI/Objects/GeometryDash/General/LevelObjectIDUsage.cs
  GDAPI/GDAPI/Objects/GeometryDash/IDTypes/BlockID.cs
  GDAPI/GDAPI/Objects/GeometryDash/IDTypes/ColorID.cs
  GDAPI/GDAPI/Objects/GeometryDash/IDTypes/GroupID.cs
  GDAPI/GDAPI/Objects/GeometryDash/IDTypes/IID.cs
  GDAPI/GDAPI/Objects/GeometryDash/IDTypes/ItemID.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/GeneralObject.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/Interfaces/IHasCopiedColorID.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/Interfaces/IHasPrimaryBlockID.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/Interfaces/IHasPrimaryID.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/Interfaces/IHasPrimaryItemID.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/Interfaces/IHasSecondaryBlockID.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/Interfaces/IHasSecondaryGroupID.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/Interfaces/IHasSecondaryID.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/Interfaces/IHasTargetColorID.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/Interfaces/IHasTargetGroupID.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/Interfaces/IHasTargetItemID.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/LevelObjectCollection.cs
Labels: enhancement

#55 Data and Gamesave.cs organization
  GDAPI/GDAPI.Tests/Functions/Extensions/StringExtensionsTests.cs
  GDAPI/GDAPI.Tests/Objects/GeometryDash/GamesaveStrings/GamesaveStringTests.cs
  GDAPI/GDAPI.Tests/Objects/GeometryDash/GamesaveStrings/GamesaveStringTestsBase.cs
  GDAPI/GDAPI.Tests/Objects/GeometryDash/GamesaveStrings/LevelDataStringTests.cs
  GDAPI/GDAPI.Tests/Objects/GeometryDash/GamesaveStrings/LevelStringTests.cs
  GDAPI/GDAPI.Tests/Resources/ResourceStrings/GamesaveCipher/Decrypted CCGameManager.txt
  GDAPI/GDAPI.Tests/Resources/ResourceStrings/GamesaveCipher/Decrypted CCLocalLevels.txt
  GDAPI/GDAPI.Tests/Resources/ResourceStrings/GamesaveCipher/Decrypted LevelString.txt
  GDAPI/GDAPI.Tests/Resources/ResourceStrings/GamesaveCipher/Encrypted CCGameManager.txt
  GDAPI/GDAPI.Tests/Resources/ResourceStrings/GamesaveCipher/Encrypted CCLocalLevels.txt
  GDAPI/GDAPI.Tests/Resources/ResourceStrings/GamesaveCipher/Encrypted LevelString.txt
  GDAPI/GDAPI.Tests/TestResourceContainer.cs
  GDAPI/GDAPI/Application/Database.cs
  GDAPI/GDAPI/Functions/Crypto/GZipCompression.cs
  GDAPI/GDAPI/Functions/Crypto/GeometryDashCrypto.cs
  GDAPI/GDAPI/Functions/Extensions/EncodedStringProcessing.cs
  GDAPI/GDAPI/Functions/Extensions/StringExtensions.cs
  GDAPI/GDAPI/Functions/GeometryDash/Gamesave.cs
  GDAPI/GDAPI/Objects/General/BaseCipherResult.cs
  GDAPI/GDAPI/Objects/General/DecryptionResult.cs
  GDAPI/GDAPI/Objects/General/EncryptionResult.cs
  GDAPI/GDAPI/Objects/GeometryDash/GamesaveStrings/BaseGamesaveString.cs
  GDAPI/GDAPI/Objects/GeometryDash/GamesaveStrings/DATFileGamesaveString.cs
  GDAPI/GDAPI/Objects/GeometryDash/GamesaveStrings/GamesaveString.cs
  GDAPI/GDAPI/Objects/GeometryDash/GamesaveStrings/LevelDataString.cs
  GDAPI/GDAPI/Objects/GeometryDash/GamesaveStrings/LevelString.cs
  GDAPI/GDAPI/Objects/GeometryDash/General/Level.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/LevelObjectCollection.cs
Labels: code quality

#60 Adjust guidelines to new findings
  GDAPI/GDAPI/Objects/GeometryDash/General/Guideline.cs
  GDAPI/GDAPI/Objects/GeometryDash/General/GuidelineCollection.cs
  GDAPI/GDAPI/Objects/GeometryDash/General/GuidelineColor.cs
Labels: closes issue

#61 Split editor into a number of pluggable components
  GDAPI/GDAPI.Tests/Application/Editors/IDMigrationTests.cs
  GDAPI/GDAPI.Tests/Objects/General/BindableTests.cs
  GDAPI/GDAPI/Application/Editors/BaseEditor.cs
  GDAPI/GDAPI/Application/Editors/BaseObjectSelectionPluggableEditor.cs
  GDAPI/GDAPI/Application/Editors/BasePluggableEditor.cs
  GDAPI/GDAPI/Application/Editors/BasicEditor.cs
  GDAPI/GDAPI/Application/Editors/Editor.cs
  GDAPI/GDAPI/Application/Editors/EditorFactory.cs
  GDAPI/GDAPI/Application/Editors/GuidelineEditor.cs
  GDAPI/GDAPI/Application/Editors/IDMigrationEditor.cs
  GDAPI/GDAPI/Application/Editors/IEditor.cs
  GDAPI/GDAPI/Application/Editors/IPluggableEditor.cs
  GDAPI/GDAPI/GDAPI.csproj
  GDAPI/GDAPI/Objects/General/Bindable.cs
  GDAPI/GDAPI/Objects/GeometryDash/LevelObjects/LevelObjectCollection.cs
  GDAPI/GDAPI/Objects/PluggableComponents/IMultiPlugeeComponent.cs
  GDAPI/GDAPI/Objects/PluggableComponents/IPlugeeComponent.cs
  GDAPI/GDAPI/Objects/PluggableComponents/IPluggableComponent.cs
Labels: code quality, enhancement
